# Generated by Django 4.2.0 on 2026-04-04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelInfo',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('cate', models.SmallIntegerField(choices=[(0, '女频'), (1, '男频'), (2, '出版')], verbose_name='类别')),
                ('img', models.CharField(blank=True, max_length=255, null=True, verbose_name='封面 URL')),
                ('name', models.CharField(max_length=255, verbose_name='书名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('up_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('up_chapter', models.CharField(blank=True, max_length=255, null=True, verbose_name='更新章节')),
                ('up_status', models.SmallIntegerField(default=0, verbose_name='连载状态')),
                ('signed', models.SmallIntegerField(default=0, verbose_name='签约状态')),
                ('vip', models.SmallIntegerField(default=0, verbose_name='VIP 状态')),
                ('category', models.CharField(max_length=100, verbose_name='分类')),
                ('sub_category', models.CharField(max_length=100, verbose_name='子分类')),
                ('wordcount', models.IntegerField(default=0, verbose_name='字数')),
                ('all_recommend', models.IntegerField(default=0, verbose_name='总推荐数')),
                ('week_recommend', models.IntegerField(default=0, verbose_name='周推荐数')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('chapters', models.IntegerField(default=0, verbose_name='章节数')),
            ],
            options={
                'verbose_name': '小说信息',
                'verbose_name_plural': '小说信息',
                'db_table': 'novel_info',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('user_cate', models.SmallIntegerField(choices=[(0, '女频'), (1, '男频'), (2, '出版')], default=1, verbose_name='用户类别')),
                ('avatar', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('selected_channel', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='选择的频道')),
                ('selected_categories', models.JSONField(blank=True, default=list, null=True, verbose_name='选择的分类')),
                ('selected_sub_categories', models.JSONField(blank=True, default=dict, null=True, verbose_name='选择的子分类')),
                ('has_set_preference', models.BooleanField(default=False, verbose_name='是否已设置偏好')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user_profile',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户 ID')),
                ('user_cate', models.SmallIntegerField(verbose_name='用户类别')),
                ('novel_id', models.IntegerField(verbose_name='小说 ID')),
                ('read_time', models.SmallIntegerField(verbose_name='阅读时长 (分钟)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
            ],
            options={
                'verbose_name': '用户行为',
                'verbose_name_plural': '用户行为',
                'db_table': 'user_behavior',
                'indexes': [
                    models.Index(fields=['user_id'], name='api_userb_user_id_idx'),
                    models.Index(fields=['novel_id'], name='api_userb_novel_id_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.SmallIntegerField(choices=[(0, '女'), (1, '男')], default=1, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='个人简介')),
                ('avatar', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
                'db_table': 'user_extend_profile',
            },
        ),
    ]
